#!/bin/sh

if [ -f cds.lib ] && [ -f CellList ]; 
then
while read line
do
array=(`echo $line | tr ' ' ' '` )
cell=${array[1]}
library=${array[0]}
echo ${library}_${cell}
done <"CellList"
elif
echo "cds.lib and CellList(contains library and cell) must be provided"

fi
